from .laplacian import process_magnetic_laplacian
from .laplacian_standard import process_magnetic_laplacian_standard
from .laplacian_sparse import process_magnetic_laplacian_sparse
from .laplacian_sparse_2 import process_magnetic_laplacian_sparse_2